"""2nd commit

Revision ID: 43eb69ad9fca
Revises: b3da5e56fc87
Create Date: 2021-11-13 16:32:13.106895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eb69ad9fca'
down_revision = 'b3da5e56fc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_column('colors')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('colors', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
